# Ansible managed

default: &default
  adapter: postgresql
  pool: 5

development:
  <<: *default
  database: snaas_api

  username: vagrant
  password: 

test:
  <<: *default
  database: snaas_api_test
